/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author ASUS
 */
public class JHomeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form JHomeEmployee
     */
    public JHomeAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        tesPanel = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        EmployeeMgt = new javax.swing.JLabel();
        JobMgt = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        RoleMgt = new javax.swing.JLabel();
        StatusMgt = new javax.swing.JLabel();
        basePanel = new javax.swing.JPanel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tesPanel.setBackground(new java.awt.Color(255, 204, 102));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Logout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("Edit User");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Admin Name");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Id Employee");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Job");

        EmployeeMgt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        EmployeeMgt.setIcon(new javax.swing.ImageIcon("D:\\Project Overtime\\icon\\cilik\\form2.png")); // NOI18N
        EmployeeMgt.setText("Employee Mgt");
        EmployeeMgt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                EmployeeMgtMouseReleased(evt);
            }
        });

        JobMgt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JobMgt.setIcon(new javax.swing.ImageIcon("D:\\Project Overtime\\icon\\cilik\\history2.png")); // NOI18N
        JobMgt.setText("Job Mgt");
        JobMgt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JobMgtMouseReleased(evt);
            }
        });

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/download.png"))); // NOI18N
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                profileMouseReleased(evt);
            }
        });
        profile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                profileKeyReleased(evt);
            }
        });

        RoleMgt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        RoleMgt.setIcon(new javax.swing.ImageIcon("D:\\Project Overtime\\icon\\cilik\\history2.png")); // NOI18N
        RoleMgt.setText("Role Mgt");
        RoleMgt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RoleMgtMouseReleased(evt);
            }
        });

        StatusMgt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        StatusMgt.setIcon(new javax.swing.ImageIcon("D:\\Project Overtime\\icon\\cilik\\history2.png")); // NOI18N
        StatusMgt.setText("Status Mgt");
        StatusMgt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                StatusMgtMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout tesPanelLayout = new javax.swing.GroupLayout(tesPanel);
        tesPanel.setLayout(tesPanelLayout);
        tesPanelLayout.setHorizontalGroup(
            tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tesPanelLayout.createSequentialGroup()
                .addGroup(tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tesPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(profile)
                        .addGap(18, 18, 18)
                        .addGroup(tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)))
                    .addGroup(tesPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoleMgt)
                            .addGroup(tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EmployeeMgt)
                                .addComponent(JobMgt))
                            .addComponent(StatusMgt)))
                    .addGroup(tesPanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tesPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton7)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        tesPanelLayout.setVerticalGroup(
            tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tesPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profile)
                    .addGroup(tesPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel23)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)))
                .addGap(76, 76, 76)
                .addComponent(EmployeeMgt)
                .addGap(32, 32, 32)
                .addComponent(JobMgt)
                .addGap(63, 63, 63)
                .addComponent(RoleMgt)
                .addGap(52, 52, 52)
                .addComponent(StatusMgt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addGap(30, 30, 30))
        );

        basePanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout basePanelLayout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(basePanelLayout);
        basePanelLayout.setHorizontalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 791, Short.MAX_VALUE)
        );
        basePanelLayout.setVerticalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void EmployeeMgtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeMgtMouseReleased
        JIEmployeeForm employeeForm = new JIEmployeeForm();
        this.basePanel.add(employeeForm);
        employeeForm.show();
    }//GEN-LAST:event_EmployeeMgtMouseReleased

    private void JobMgtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobMgtMouseReleased
        JIJobForm jobForm = new JIJobForm();
        this.basePanel.add(jobForm);
        jobForm.show();
    }//GEN-LAST:event_JobMgtMouseReleased

    private void profileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_profileKeyReleased
        
    }//GEN-LAST:event_profileKeyReleased

    private void profileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseReleased
        JIProfileForm profileForm = new JIProfileForm();
        this.basePanel.add(profileForm);
        profileForm.show();
    }//GEN-LAST:event_profileMouseReleased

    private void RoleMgtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoleMgtMouseReleased
        JIRoleForm roleForm = new JIRoleForm();
        this.basePanel.add(roleForm);
        roleForm.show();
    }//GEN-LAST:event_RoleMgtMouseReleased

    private void StatusMgtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatusMgtMouseReleased
        JIStatusForm statusForm = new JIStatusForm();
        this.basePanel.add(statusForm);
        statusForm.show();
    }//GEN-LAST:event_StatusMgtMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JHomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmployeeMgt;
    private javax.swing.JLabel JobMgt;
    private javax.swing.JLabel RoleMgt;
    private javax.swing.JLabel StatusMgt;
    private javax.swing.JPanel basePanel;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel profile;
    private javax.swing.JPanel tesPanel;
    // End of variables declaration//GEN-END:variables
}
