/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.EmployeeController;
import controllers.EmployeeRoleController;
import controllers.JobController;
import controllers.RoleController;
import icontrollers.IEmployeeController;
import icontrollers.IEmployeeRoleController;
import icontrollers.IJobController;
import icontrollers.IRoleController;
import models.EmployeeRole;
import org.hibernate.SessionFactory;
import session.UserSession;
import tools.HibernateUtil;

/**
 *
 * @author ASUS
 */
public class JHomeEmployee extends javax.swing.JFrame {

    SessionFactory factory = HibernateUtil.getSessionFactory();
    IEmployeeController iec = new EmployeeController(factory);
    IJobController ijc = new JobController(factory);
    IEmployeeRoleController ierc = new EmployeeRoleController(factory);
    IRoleController irc = new RoleController(factory);

//    String id = UserSession.getIdUser();
//    String name = UserSession.getUsername();
//    String job = UserSession.getJob();
    /**
     * Creates new form JHomeEmployee
     */
    public JHomeEmployee() {
        initComponents();
        UserSession us = new UserSession();
        String idRole = "";
        String role = "";
        for (EmployeeRole employeeRole : ierc.search(us.getIdUser())) {
            role = employeeRole.getRole().getName();
        }
        lblUser.setText("Hello, "+us.getUsername());
        lblId.setText(us.getIdUser());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanel = new javax.swing.JPanel();
        tesPanel = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        btnHistory = new javax.swing.JButton();
        btnOvertimeReq = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        basePanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout basePanelLayout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(basePanelLayout);
        basePanelLayout.setHorizontalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );
        basePanelLayout.setVerticalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tesPanel.setBackground(new java.awt.Color(255, 255, 102));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Logout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("Edit User");

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(51, 51, 51));
        lblUser.setText("HR Name");

        lblId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblId.setForeground(new java.awt.Color(51, 51, 51));
        lblId.setText("Id");

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/download.png"))); // NOI18N
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                profileMouseReleased(evt);
            }
        });
        profile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                profileKeyReleased(evt);
            }
        });

        btnHistory.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/history2.png"))); // NOI18N
        btnHistory.setText("History");
        btnHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistoryMouseClicked(evt);
            }
        });

        btnOvertimeReq.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnOvertimeReq.setText("Overtime Request");
        btnOvertimeReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOvertimeReqMouseClicked(evt);
            }
        });
        btnOvertimeReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOvertimeReqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tesPanelLayout = new javax.swing.GroupLayout(tesPanel);
        tesPanel.setLayout(tesPanelLayout);
        tesPanelLayout.setHorizontalGroup(
            tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tesPanelLayout.createSequentialGroup()
                .addGroup(tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tesPanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tesPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOvertimeReq)
                            .addGroup(tesPanelLayout.createSequentialGroup()
                                .addComponent(profile)
                                .addGap(18, 18, 18)
                                .addGroup(tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUser)
                                    .addComponent(lblId)))
                            .addComponent(btnHistory)))
                    .addGroup(tesPanelLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton7)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        tesPanelLayout.setVerticalGroup(
            tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tesPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profile)
                    .addGroup(tesPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblId)))
                .addGap(66, 66, 66)
                .addComponent(btnOvertimeReq)
                .addGap(44, 44, 44)
                .addComponent(btnHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton7)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void profileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseReleased
        JIProfileForm profileForm = new JIProfileForm();
        this.basePanel.add(profileForm);
        profileForm.show();
    }//GEN-LAST:event_profileMouseReleased

    private void profileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_profileKeyReleased

    }//GEN-LAST:event_profileKeyReleased

    private void btnHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMouseClicked
        JIOvertimeRequestStatus requestStatus = new JIOvertimeRequestStatus();
        this.basePanel.add(requestStatus);
        requestStatus.show();
    }//GEN-LAST:event_btnHistoryMouseClicked

    private void btnOvertimeReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOvertimeReqMouseClicked
        JIOvertimeRequestForm overtimeRequestForm = new JIOvertimeRequestForm();
        this.basePanel.add(overtimeRequestForm);
        overtimeRequestForm.show();
    }//GEN-LAST:event_btnOvertimeReqMouseClicked

    private void btnOvertimeReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOvertimeReqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOvertimeReqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JHomeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JHomeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JHomeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JHomeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JHomeEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basePanel;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnOvertimeReq;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel profile;
    private javax.swing.JPanel tesPanel;
    // End of variables declaration//GEN-END:variables

}
