/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.EmployeeController;
import controllers.EmployeeJobController;
import controllers.EmployeeRoleController;
import controllers.JobController;
import controllers.RoleController;
import icontrollers.IEmployeeController;
import icontrollers.IEmployeeJobController;
import icontrollers.IEmployeeRoleController;
import icontrollers.IJobController;
import icontrollers.IRoleController;
import models.EmployeeJob;
import models.EmployeeRole;
import org.hibernate.SessionFactory;
import session.UserSession;
import tools.HibernateUtil;

/**
 *
 * @author ASUS
 */
public class JHomeHR extends javax.swing.JFrame {

    SessionFactory factory = HibernateUtil.getSessionFactory();
    IEmployeeController iec = new EmployeeController(factory);
    IJobController ijc = new JobController(factory);
    IEmployeeJobController iej = new EmployeeJobController(factory);
    IEmployeeRoleController ierc = new EmployeeRoleController(factory);
    IRoleController irc = new RoleController(factory);
    
    /**
     * Creates new form JHomeEmployee
     */
    public JHomeHR() {
        initComponents();
        UserSession us = new UserSession();
        String idRole = "";
        String role = "";
        String job = "";
        for (EmployeeJob employeeJob : iej.search(us.getIdUser())) {
            role = employeeJob.getJob().getName();
        }
        lblHr.setText("Hello, "+us.getUsername());
        lblId.setText(us.getIdUser());
        lblJob.setText(us.getJob());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tesPanel = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        lblHr = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblJob = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        btnApproval = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        basePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        tesPanel.setBackground(new java.awt.Color(255, 255, 102));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Logout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("Edit User");

        lblHr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHr.setForeground(new java.awt.Color(51, 51, 51));
        lblHr.setText("HR Name");

        lblId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblId.setForeground(new java.awt.Color(51, 51, 51));
        lblId.setText("Id Employee");

        lblJob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblJob.setForeground(new java.awt.Color(51, 51, 51));
        lblJob.setText("Job");

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/download.png"))); // NOI18N
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                profileMouseReleased(evt);
            }
        });
        profile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                profileKeyReleased(evt);
            }
        });

        btnApproval.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnApproval.setText("Overtime Approval");
        btnApproval.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnApprovalMouseClicked(evt);
            }
        });

        btnReport.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnReport.setText("Report");
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tesPanelLayout = new javax.swing.GroupLayout(tesPanel);
        tesPanel.setLayout(tesPanelLayout);
        tesPanelLayout.setHorizontalGroup(
            tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tesPanelLayout.createSequentialGroup()
                .addGroup(tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tesPanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tesPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnApproval)
                            .addGroup(tesPanelLayout.createSequentialGroup()
                                .addComponent(profile)
                                .addGap(18, 18, 18)
                                .addGroup(tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHr)
                                    .addComponent(lblId)
                                    .addComponent(lblJob)))
                            .addComponent(btnReport)))
                    .addGroup(tesPanelLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton7)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        tesPanelLayout.setVerticalGroup(
            tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tesPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(tesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profile)
                    .addGroup(tesPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblHr)
                        .addGap(7, 7, 7)
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJob)))
                .addGap(131, 131, 131)
                .addComponent(btnApproval)
                .addGap(38, 38, 38)
                .addComponent(btnReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(49, 49, 49))
        );

        basePanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout basePanelLayout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(basePanelLayout);
        basePanelLayout.setHorizontalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        basePanelLayout.setVerticalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void profileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_profileKeyReleased
        
    }//GEN-LAST:event_profileKeyReleased

    private void profileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseReleased
        JIProfileForm profileForm = new JIProfileForm();
        this.basePanel.add(profileForm);
        profileForm.show();
    }//GEN-LAST:event_profileMouseReleased

    private void btnApprovalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApprovalMouseClicked
        JIOvertimeApproval overtimeApproval  = new JIOvertimeApproval();
        this.basePanel.add(overtimeApproval);
        overtimeApproval.show();
    }//GEN-LAST:event_btnApprovalMouseClicked

    private void btnReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JHomeHR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JHomeHR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JHomeHR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JHomeHR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JHomeHR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basePanel;
    private javax.swing.JButton btnApproval;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel lblHr;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblJob;
    private javax.swing.JLabel profile;
    private javax.swing.JPanel tesPanel;
    // End of variables declaration//GEN-END:variables
}
